### ISSUE TITLE
Fix code scanning alert - Server-side request forgery

### ISSUE THREAD

**Issue by ymw0407** [AgainIoT/Open-Set-Go_server#104]
Tracking issue for:
- [ ] https://github.com/AgainIoT/Open-Set-Go_server/security/code-scanning/2

**Comment by ymw0407** [comment]
Since there is currently no good way to solve this problem, I think it should be solved by embedding a license or using octokit. I think it would be good to share opinions on that part.
해당 문제에 대해서는 현재 좋은 방법이 없기 때문에 License를 내장시키거나 octokit을 사용하는 방식을 통해서 해결해야될 것 같습니다. 해당 부분에 대해서 의견을 나눠보면 좋을 것 같습니다.

@Kim-Jiyun

**Comment by Kim-Jiyun** [comment]
I think the built-in license may cause problems in the future. Furthermore, there are licenses that should not conflict, and if you embed those licenses in the repository, you can judge from the outside that there is a license conflict. I think it's time to find a way to avoid this as much as possible.

License를 내장시키는 것은 추후에 문제가 발생할 수도 있다고 생각합니다. 더더욱 충돌이 나면 안되는 라이센스들도 있는데, repository에 그러한 License들을 내장시킨다면 License 충돌이 있다라고 외부에서 판단할 수 있을 것이라고 생각됩니다. 이러한 부분은 최대한 피해서 하는 방식을 찾아볼 시간인 것 같습니다.
