### ISSUE TITLE
Singleton pattern is stateful

### ISSUE THREAD

**Issue by ymw0407** [AgainIoT/Open-Set-Go_server#12]
OcotoClient class에 사용된 싱글톤 패턴에 문제가 있습니다. 기본적으로 서버에서 사용하는 모듈들은(특히 라우팅에 사용될 모듈들은 더더욱)  stateless, 즉 상태를 저장하면 안됩니다.
해당 API를 여러 사용자들이 한 서버의 있는 자원을 통해 활용할 것이기 때문에 상태를 저장하는 것은 오직, DataBase만이 되어야 합니다.
따라서, 싱글톤 패턴을 적용하고자 한다면 stateless하게 만들어야 합니다. 그렇기 때문에, 해당 클래스에서는 싱글톤 패턴을 사용하는 것이 적절하지 않은 것으로 보입니다.
혹은, 싱글톤 패턴을 적용하고자 한다면 이후에 userDB를 만들고, userName과 token 자체를 DB에 저장하고 가져와서 사용하는 방식을 택하여 해당 클래스가 stateless하도록 만들어야 할 것으로 보입니다.

**Comment by bentshrimp** [comment]
It turns out that OctoClient ain't singleton pattern. Haha my bad, I should've studied thoroughly.

**Comment by bentshrimp** [comment]
Now we migrate to NestJS #14. We don't use OctokitClient anymore. And now I know what singleton pattern is.
