### ISSUE TITLE
🐛 [BUG] - upload gitignore files has problem

### ISSUE THREAD

**Issue by ymw0407** [AgainIoT/Open-Set-Go_server#62]
### Browsers

Chrome

### OS

Linux

### Description

If you select gitignore file and framework, there is a bug that applies only one of them.
gitignore file과 framework를 선택하면, 둘 중 하나만 적용되는 버그가 존재한다.

### Reproduction URL

http://localhost:8080/file

### Reproduction Steps

```bash
.
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

**Comment by bentshrimp** [comment]
This problem happens because makeGitignore() and makeFramework() both generates .gitignore files. Then, uploadFiles() uploads or updates one of them these .gitignore file.
To fix it, we should combine these two .gitignore file every time we upload files.
