### ISSUE TITLE
🚀 [REQUEST] - Improving Issue Template

### ISSUE THREAD

**Issue by ymw0407** [AgainIoT/Open-Set-Go_server#95]
### Describe

Adding New Issue Template for maintainers & Improve overall Issue Templates
maintainer들을 위한 새로운 Issue Template 추가하기 & 전반적인 Issue Template들 개선

### Reasons

I'm currently using three Issue Template, but it seems that there is something to be supplemented after using it so far. We will improve the Issue Template accordingly.

---
Issue Template을 현재 3가지 사용하고 있는데, 지금까지 사용해본 결과 보완할 점이 있어보인다. 이에 맞추어 Issue Template을 개선해볼 것이다.

### Connection

- [X] Have no effect on other functions
- [ ] Other functions need to be changed

**Comment by ymw0407** [comment]
@Kim-Jiyun @bentshrimp 
Please check and comment on changing which parts each want to improve!
각자 어떤 부분을 개선하고 싶은지 확인하고 변경하는데에 의견을 주세요!

**Comment by bentshrimp** [comment]
![image](https://github.com/AgainIoT/Open-Set-Go_server/assets/39232867/60028180-cecb-414e-bf6b-12cd1902c024)

new feature의 용도는 '새로운 기능 제안'과 '새로운 업무 공지'입니다. '새로운 기능 제안'의 경우, 이러한 reasons(이유)로 이 기능을 추가한다는 describe(설명)을 작성하기 적합합니다. 하지만 '새로운 업무 공지'일 경우, 마땅히 적을 이유는 없지만 reasons가 필수항목이라 난감했던 경험이 있습니다.

**Comment by ymw0407** [comment]
> ![image](https://user-images.githubusercontent.com/39232867/270256370-60028180-cecb-414e-bf6b-12cd1902c024.png)
> 
> new feature의 용도는 '새로운 기능 제안'과 '새로운 업무 공지'입니다. '새로운 기능 제안'의 경우, 이러한 reasons(이유)로 이 기능을 추가한다는 describe(설명)을 작성하기 적합합니다. 하지만 '새로운 업무 공지'일 경우, 마땅히 적을 이유는 없지만 reasons가 필수항목이라 난감했던 경험이 있습니다.
> 
> 그래서 reasons를 필수 항목에서 제외하거나, new feature를 앞에서 언급한 용도대로 두 템플릿으로 나누길 제안합니다.

좋은 방법인 것 같습니다. Description을 필수로 사용하고, reason을 선택으로 사용하는 것도 하나의 방법일 것 같습니다.
